services:
  - type: web
    name: arxiv-discord-bot
    env: python
    autoDeploy: true
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: DATABASE_NAME
        value: /tmp/papers.db
